Final
Appolinariya1/AQA_MTS_Graduate_work pull request #4
Opened 2024-04-30 12:27 UTC by Appolinariya1

2024-04-30 14:54 UTC, wildpioneer requested changes

2024-04-30 14:54 UTC, wildpioneer commented on AQA_MTS_Graduate_work/Graduate_work/Tests/API/ProjectTests.cs
> +        string projectJson = File.ReadAllText(@"Resources\test_Project.json");
Этот слеш не всегда работает на маке - нужно почитать как соединять путь

2024-04-30 14:54 UTC, wildpioneer commented on AQA_MTS_Graduate_work/Graduate_work/Tests/GUI/DeleteProjectTest.cs
> +    public void DeleteOneProjectTest()
Падает данный тест

2024-06-10 21:02 UTC, Appolinariya1 commented on AQA_MTS_Graduate_work/Graduate_work/Tests/API/ProjectTests.cs
> +        string projectJson = File.ReadAllText(@"Resources\test_Project.json");
исправила

2024-06-10 21:02 UTC, Appolinariya1 commented on AQA_MTS_Graduate_work/Graduate_work/Tests/GUI/DeleteProjectTest.cs
> +    public void DeleteOneProjectTest()
В момент запуска вами я чистила в учетке Qase старые проекты и могла случайно вручную удалить созданный проект для теста удаления. Запустила - работает :)

2024-06-10 21:03 UTC, merged